[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    ESP Async WebServer @ ^3.3.23
    AsyncTCP @ ^3.3.6
    bblanchon/ArduinoJson @ ^7.3.1
